import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger,  SidebarInset} from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import {Lexend} from "next/font/google"

const lexend = Lexend({subsets: ["latin"]});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <SidebarProvider>
          <AppSidebar />

          {/* 👇 SidebarInset sẽ tự xử lý phần “còn lại sau sidebar” + responsive */}
          <SidebarInset className="min-h-dvh flex flex-col min-w-0">
            {/* Trigger cho mobile */}
            <div className="md:hidden p-2">
              <SidebarTrigger />
            </div>

            {/* vùng nội dung thực sự */}
            <main className="flex-1 min-w-0">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}